Repository pesto-students/batch-8-NuSlack, pull requests merged in 2019-07, with the labels that each got.

#6 docs: update the README
  README.md
Labels: README

#7 chore: Add the initial config for CircleCI
  .circleci/config.yml
Labels: CI/CD

#18 Update the circleci config for client and server
  .circleci/config.yml
  client/yarn.lock
Labels: CI/CD

#17 Add test scripts in server, client and root
  package.json
  server/package.json
  server/src/test/pass.test.js
  server/yarn.lock
  yarn.lock
Labels: SETUP

#9 Complete : add eslint, husky and commitlint
  .eslintrc
  .prettierrc
  client/package.json
  commitlint.config.js
  package.json
  server/src/app.js
  yarn.lock
Labels: SETUP

#27 chore: setup project configs on heroku and circleci - trigger build
  .circleci/config.yml
  .circleci/setup-heroku.sh
Labels: CI/CD

#28 Chore: Add deployment instructions for netlify via circleci
  .circleci/config.yml
Labels: CI/CD

#20 Add socket.io for messaging
  server/.env.template
  server/package.json
  server/src/Schemas/channels.js
  server/src/Schemas/messages.js
  server/src/Schemas/tableNames.js
  server/src/Schemas/users.js
  server/src/__mocks__/setup.js
  server/src/config/database.js
  server/src/index.js
  server/src/setup.js
  server/src/socket/eventNames.js
  server/src/socket/index.js
  server/src/test/pass.test.js
  server/src/test/socket-communication.test.js
  server/yarn.lock
Labels: socket-core

#32 Complete - fix warnings in react build and linting issues
  client/src/components/ChatComponent/index.js
  client/src/components/ChatInputBox/index.js
  client/src/components/CircleButton/index.js
  client/src/components/MainHeader/__test__/__snapshots__/mainHeader.test.js.snap
  client/src/components/MainHeader/index.js
  client/src/components/Sidebar/index.js
Labels: cleanup

#33 Complete fix: add _redirects file to redirect netlify routes to root
  client/public/_redirects
Labels: netlify-fixes

#24 Add Rest API
  server/src/constants/failedResponse.js
  server/src/controllers/channels.js
  server/src/controllers/messages.js
  server/src/controllers/users.js
  server/src/controllers/users/get.js
  server/src/controllers/users/index.js
  server/src/index.js
  server/src/routes/channels.js
  server/src/routes/index.js
  server/src/routes/messages.js
  server/src/routes/users.js
  server/src/test/channelController.test.js
  server/src/test/messagesController.test.js
  server/src/test/userController.test.js
  server/src/utils/tests.js
Labels: enhancement

#59 Complete feat(client-app-context): add global context and methods to update it
  client/.env.template
  client/package.json
  client/src/config/index.js
  client/src/config/local-storage-keys.js
  client/src/config/server.js
  client/src/context/HomeContext/__test__/reducer.test.js
  client/src/context/HomeContext/action-handlers.js
  client/src/context/HomeContext/actions-types.js
  client/src/context/HomeContext/api.js
  client/src/context/HomeContext/index.js
  client/src/context/HomeContext/reducer.js
  client/src/context/HomeContext/state.js
  client/yarn.lock
Labels: SETUP, context, enhancement

#66 Complete : add socket client in react app and integrate with context module
  client/.env.template
  client/.gitignore
  client/package.json
  client/src/constants/eventNames.js
  client/src/context/HomeContext/index.js
  client/src/socket/emit.js
  client/src/socket/index.js
  client/yarn.lock
Labels: socket-client

#57 Complete: Add SmallButton, ChannelForm and ChannelModal components
  client/src/components/AddChannelForm/__test__/__snapshots__/addChannelForm.test.js.snap
  client/src/components/AddChannelForm/__test__/addChannelForm.test.js
  client/src/components/AddChannelForm/index.js
  client/src/components/AddChannelModal/__test__/__snapshots__/addChannelModal.test.js.snap
  client/src/components/AddChannelModal/__test__/addChannelModal.test.js
  client/src/components/AddChannelModal/index.js
  client/src/components/SmallButton/__test__/__snapshots__/smallButton.test.js.snap
  client/src/components/SmallButton/__test__/smallButton.test.js
  client/src/components/SmallButton/index.js
Labels: base-design

#72 Complete : feat(login-page): add login page and on login redirect to home
  client/.env.template
  client/src/API/index.js
  client/src/App.js
  client/src/Router.js
  client/src/components/LoginPage/__test__/__snapshots__/loginPage.test.js.snap
  client/src/components/LoginPage/__test__/loginPage.test.js
  client/src/components/LoginPage/index.js
  client/src/components/LoginPage/style.js
  client/src/components/MainHeader/__test__/__snapshots__/mainHeader.test.js.snap
  client/src/components/MainHeader/index.js
  client/src/components/SmallButton/__test__/__snapshots__/smallButton.test.js.snap
  client/src/components/home/__test__/__snapshots__/home.test.js.snap
  client/src/components/home/index.js
  client/src/config/server.js
  client/src/custom-hooks/__test__/useApiHook.test.js
  client/src/custom-hooks/index.js
  client/src/index.js
Labels: enhancement, user-login

#77 Complete : fix(socket-client): fixes client connection and online/offline issues
  .vscode/launch.json
  client/src/components/ChatComponent/__test__/__snapshots__/chatComponent.test.js.snap
  client/src/components/ChatInputBox/__test__/__snapshots__/chatInputBook.test.js.snap
  client/src/context/HomeContext/index.js
  client/src/socket/index.js
  server/package.json
Labels: socket-client, socket-core

#81 Complete : feat(one-to-one): add one to one chat support
  client/src/components/ChatComponent/index.js
  client/src/components/ChatInputBox/index.js
  client/src/components/Sidebar/index.js
  client/src/context/HomeContext/action-handlers.js
  client/src/context/HomeContext/actions-types.js
  client/src/context/HomeContext/api.js
  client/src/context/HomeContext/index.js
  client/src/context/HomeContext/reducer.js
  client/src/context/HomeContext/state.js
  client/src/socket/index.js
  server/src/controllers/messages.js
  server/src/routes/messages.js
  server/src/socket/handlers/handleConnectedUser.js
  server/src/socket/handlers/handleMessage.js
  server/src/test/socket-communication.test.js
Labels: feat: one-to-one-chat

#96 [WIP] User Profile Page and related enhancements
  .circleci/config.yml
  client/.env.test
  client/src/API/index.js
  client/src/Router.js
  client/src/components/LoginPage/__test__/__snapshots__/loginPage.test.js.snap
  client/src/components/LoginPage/index.js
  client/src/components/MainHeader/__test__/__snapshots__/mainHeader.test.js.snap
  client/src/components/MainHeader/index.js
  client/src/components/ProfilePage/index.js
  client/src/components/ProfilePage/profile-edit-form.js
  client/src/components/ProfilePage/style.js
  client/src/context/HomeContext/index.js
  client/src/context/HomeContext/reducer.js
  client/src/custom-hooks/index.js
  client/src/setupTests.js
Labels: enhancement, feat: user-profile

#109 Complete : feat(color-scheme): update primary color
  client/config-overrides.js
  client/src/components/ChatHeader/index.js
  client/src/components/MainHeader/index.js
  client/src/components/home-layout/__test__/__snapshots__/homeLayout.test.js.snap
  client/src/components/home-layout/index.js
Labels: UI, base-design

#147 Complete : fix: header responsiveness fixed
  client/public/images/transparent-logo-small.png
  client/src/components/LoginForm/__test__/__snapshots__/loginForm.test.js.snap
  client/src/components/LoginForm/__test__/loginForm.test.js
  client/src/components/LoginForm/index.js
  client/src/components/MainHeader/__test__/__snapshots__/mainHeader.test.js.snap
  client/src/components/MainHeader/index.js
Labels: UI

#151 Complete : feat(teams): add `activeTeam` to localStorage
  client/src/components/MainHeader/__test__/__snapshots__/mainHeader.test.js.snap
  client/src/components/MainHeader/index.js
  client/src/components/TeamsList/index.js
  client/src/components/home-layout/__test__/__snapshots__/homeLayout.test.js.snap
  client/src/components/home/index.js
  client/src/context/HomeContext/action-handlers.js
  client/src/context/HomeContext/state.js
Labels: enhancement
